apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv
  namespace: jenkins
spec:
  storageClassName: maven-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/maven-volume/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: maven-cache
  namespace: jenkins
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: maven-pv
