pipeline {
    agent {
        kubernetes {
            label 'maven'
            yaml """
spec:
  containers:
  - name: maven
    image: maven:3-alpine
    command:
        - cat
    tty: true
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container("maven") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container("maven") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                agent {
                    kubernetes {
                        label 'dind'
                        yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
    - name: 
      image: docker.tartismaliyiz.com/jenkins-docker-maven-agent:0.1
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
"""
                    }
                }
                container ("dind") {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
