pipeline {
    agent {
        kubernetes {
            label 'jenkins-docker-maven-agent'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
    - name: jenkins-docker-maven-agent
      image: docker.tartismaliyiz.com/jenkins-docker-maven-agent:0.1
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: DOCKER_REPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-repo-credentials
              key: password
        - name: DOCKER_REPO_USER
          valueFrom:
            secretKeyRef:
              name: docker-repo-credentials
              key: username
    - name: dind
      image: docker:18.09-dind
      command:
        - dockerd-entrypoint.sh
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container("jenkins-docker-maven-agent") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container("jenkins-docker-maven-agent") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                container ("jenkins-docker-maven-agent") {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
