apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
spec:
  storageClassName: nexus-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nexus-volume/
